// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package RSA_2;

import javax.xml.rpc.*;

public interface WSInterface extends javax.xml.rpc.Service {
    public RSA_2.WSInterfacePort getWSInterfacePort() throws ServiceException;
}
