// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package RSA_2;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.util.exception.LocalizableExceptionAdapter;

public class WSInterfacePort_doProcess_RequestStruct_SOAPBuilder implements SOAPInstanceBuilder {
    private RSA_2.WSInterfacePort_doProcess_RequestStruct _instance;
    private java.lang.String in0;
    private static final int myIN0_INDEX = 0;
    
    public WSInterfacePort_doProcess_RequestStruct_SOAPBuilder() {
    }
    
    public void setIn0(java.lang.String in0) {
        this.in0 = in0;
    }
    
    public int memberGateType(int memberIndex) {
        switch (memberIndex) {
            case myIN0_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            default:
                throw new IllegalArgumentException();
        }
    }
    
    public void construct() {
    }
    
    public void setMember(int index, java.lang.Object memberValue) {
        try {
            switch(index) {
                case myIN0_INDEX:
                    _instance.setIn0((java.lang.String)memberValue);
                    break;
                default:
                    throw new java.lang.IllegalArgumentException();
            }
        }
        catch (java.lang.RuntimeException e) {
            throw e;
        }
        catch (java.lang.Exception e) {
            throw new DeserializationException(new LocalizableExceptionAdapter(e));
        }
    }
    
    public void initialize() {
    }
    
    public void setInstance(java.lang.Object instance) {
        _instance = (RSA_2.WSInterfacePort_doProcess_RequestStruct)instance;
    }
    
    public java.lang.Object getInstance() {
        return _instance;
    }
}
