// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package RSA_2;


public class WSInterfacePort_doProcess_RequestStruct {
    protected java.lang.String in0;
    
    public WSInterfacePort_doProcess_RequestStruct() {
    }
    
    public WSInterfacePort_doProcess_RequestStruct(java.lang.String in0) {
        this.in0 = in0;
    }
    
    public java.lang.String getIn0() {
        return in0;
    }
    
    public void setIn0(java.lang.String in0) {
        this.in0 = in0;
    }
}
