// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package RSA_2;


public class WSInterfacePort_doProcess_ResponseStruct {
    protected java.lang.String doProcessReturn;
    
    public WSInterfacePort_doProcess_ResponseStruct() {
    }
    
    public WSInterfacePort_doProcess_ResponseStruct(java.lang.String doProcessReturn) {
        this.doProcessReturn = doProcessReturn;
    }
    
    public java.lang.String getDoProcessReturn() {
        return doProcessReturn;
    }
    
    public void setDoProcessReturn(java.lang.String doProcessReturn) {
        this.doProcessReturn = doProcessReturn;
    }
}
