// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package RSA_2;

public interface WSInterfacePort extends java.rmi.Remote {
    public java.lang.String doProcess(java.lang.String in0) throws 
         java.rmi.RemoteException;
}
