// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package RSA_2;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.client.ServiceExceptionImpl;
import com.sun.xml.rpc.util.exception.*;
import com.sun.xml.rpc.soap.SOAPVersion;
import com.sun.xml.rpc.client.HandlerChainImpl;
import javax.xml.rpc.*;
import javax.xml.rpc.encoding.*;
import javax.xml.rpc.handler.HandlerChain;
import javax.xml.rpc.handler.HandlerInfo;
import javax.xml.namespace.QName;

public class WSInterface_Impl extends com.sun.xml.rpc.client.BasicService implements WSInterface {
    private static final QName serviceName = new QName("http://wsdl.tempuri.org", "WSInterface");
    private static final QName ns1_WSInterfacePort_QNAME = new QName("http://wsdl.tempuri.org", "WSInterfacePort");
    private static final Class WSInterfacePort_PortClass = RSA_2.WSInterfacePort.class;
    
    public WSInterface_Impl() {
        super(serviceName, new QName[] {
                        ns1_WSInterfacePort_QNAME
                    },
            new RSA_2.WSInterface_SerializerRegistry().getRegistry());
        
    }
    
    public java.rmi.Remote getPort(javax.xml.namespace.QName portName, java.lang.Class serviceDefInterface) throws javax.xml.rpc.ServiceException {
        try {
            if (portName.equals(ns1_WSInterfacePort_QNAME) &&
                serviceDefInterface.equals(WSInterfacePort_PortClass)) {
                return getWSInterfacePort();
            }
        } catch (Exception e) {
            throw new ServiceExceptionImpl(new LocalizableExceptionAdapter(e));
        }
        return super.getPort(portName, serviceDefInterface);
    }
    
    public java.rmi.Remote getPort(java.lang.Class serviceDefInterface) throws javax.xml.rpc.ServiceException {
        try {
            if (serviceDefInterface.equals(WSInterfacePort_PortClass)) {
                return getWSInterfacePort();
            }
        } catch (Exception e) {
            throw new ServiceExceptionImpl(new LocalizableExceptionAdapter(e));
        }
        return super.getPort(serviceDefInterface);
    }
    
    public RSA_2.WSInterfacePort getWSInterfacePort() {
        java.lang.String[] roles = new java.lang.String[] {};
        HandlerChainImpl handlerChain = new HandlerChainImpl(getHandlerRegistry().getHandlerChain(ns1_WSInterfacePort_QNAME));
        handlerChain.setRoles(roles);
        RSA_2.WSInterfacePort_Stub stub = new RSA_2.WSInterfacePort_Stub(handlerChain);
        try {
            stub._initialize(super.internalTypeRegistry);
        } catch (JAXRPCException e) {
            throw e;
        } catch (Exception e) {
            throw new JAXRPCException(e.getMessage(), e);
        }
        return stub;
    }
}
