// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package RSA_2;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.util.exception.LocalizableExceptionAdapter;

public class WSInterfacePort_doProcess_ResponseStruct_SOAPBuilder implements SOAPInstanceBuilder {
    private RSA_2.WSInterfacePort_doProcess_ResponseStruct _instance;
    private java.lang.String doProcessReturn;
    private static final int myDOPROCESSRETURN_INDEX = 0;
    
    public WSInterfacePort_doProcess_ResponseStruct_SOAPBuilder() {
    }
    
    public void setDoProcessReturn(java.lang.String doProcessReturn) {
        this.doProcessReturn = doProcessReturn;
    }
    
    public int memberGateType(int memberIndex) {
        switch (memberIndex) {
            case myDOPROCESSRETURN_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            default:
                throw new IllegalArgumentException();
        }
    }
    
    public void construct() {
    }
    
    public void setMember(int index, java.lang.Object memberValue) {
        try {
            switch(index) {
                case myDOPROCESSRETURN_INDEX:
                    _instance.setDoProcessReturn((java.lang.String)memberValue);
                    break;
                default:
                    throw new java.lang.IllegalArgumentException();
            }
        }
        catch (java.lang.RuntimeException e) {
            throw e;
        }
        catch (java.lang.Exception e) {
            throw new DeserializationException(new LocalizableExceptionAdapter(e));
        }
    }
    
    public void initialize() {
    }
    
    public void setInstance(java.lang.Object instance) {
        _instance = (RSA_2.WSInterfacePort_doProcess_ResponseStruct)instance;
    }
    
    public java.lang.Object getInstance() {
        return _instance;
    }
}
